name: Cypress Tests

on:
  push:
    branches:
      - '**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes no Cypress (Chrome)
        run: npx cypress run --browser chrome
